services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8083:8082
      - 5052:5051
    tty: true
    volumes:
      - ./:/app
      - ./uploads:/uploads 
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - ./uploads:/uploads
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:
