services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8082:8082
      - 5050:5050
    tty: true
    volumes:
      - ./:/app
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev"]
      interval: 5s
      timeout: 5s
      retries: 5
