services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .

databases:
  - type: database
    name: db
    plan: free
    user: postgres
