# Exported from Render on 2025-02-22T14:16:08Z
services:
- type: web
  name: academy_portfolio
  runtime: docker
  repo: https://github.com/yuta-ono845/academy_portfolio
  plan: free
  region: singapore
  dockerCommand: java -jar /app/app.jar
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"


# Exported from Render on 2025-02-22T13:20:43Z
databases:
- name: postgres
  databaseName: postgres_u11b
  user: postgres_u11b_user
  plan: free
  region: singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "13"
version: "1"
